FROM python:3.9-buster AS builder-stage

COPY ./requirements.txt .
RUN pip install --user -r requirements.txt


FROM python:3.9-slim-buster AS runner
COPY --from=builder-stage /root/.local /root/.local

# Make sure scripts in .local are usable:
RUN chmod -R 777 /root/.local
ENV PATH $PATH:/root/.local/bin

RUN apt-get update
RUN apt-get install -y sudo

# see https://qiita.com/yama07/items/a521234dc91f923ba655
# 一般ユーザ名を設定
ENV USER_NAME=developer

# sudoを使用できるようにする
RUN mkdir -p /etc/sudoers.d/
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${USER_NAME}

# 一般ユーザがユーザ/グループを追加できるようにする
# entrypoint.sh内でパーミッションを元に戻す
RUN chmod u+s /usr/sbin/useradd \
    && chmod u+s /usr/sbin/groupadd

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
